services:
  dind:
    image: docker-in-docker-custom
    build: .
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    command: ["dockerd", "--host=unix:///var/run/docker.sock"]
    volumes:
      - /var/lib/docker
